name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run unit tests
        run: go test ./...
